---
title: factoextra+ggpubr+ggplot2-层次聚类图添加标签及箱线图
author: Xwyturbo
date: '2022-11-16'
slug: factoextra+ggpubr+ggplot2-层次聚类图添加标签及箱线图
categories:
  - R
tags:
  - R Markdown
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


#  1.数据的预处理
```{r}
  library(readxl)
  library(readxl)
  library(tidyverse)
  library(bruceR)
  library(writexl)
  library(ggpubr)
  library(plotly)
  sui_de_initial <- read_xlsx("D:/wenyu/Rrojects/sui_de/sui_de_1107/sui_de_initial.xlsx")
  sd_data <- read_xlsx("D:/wenyu/Rrojects/sui_de/sui_de_1107/14种土地利用亚类面积.xlsx")
  
  #  计算每个村庄每种地类的占村庄全部用地的比重。
  sd1 <- sd_data/rowSums(sd_data)
  #  计算县域范围内每种地类占全部用地的比重
  sd2 <- colSums(sd_data)/sum(sd_data)
  
  #  按照14个亚类计算土地利用强度。
  sd_data  <- as_tibble(sd_data)
  sd_dataset <- sd_data %>% 
    mutate(lq1 = sd1$科教文卫用地/sd2[1],
           lq2 = sd1$交通运输用地/sd2[2],
           lq3 = sd1$林地/sd2[3],
           lq4 = sd1$园地/sd2[4],
           lq5 = sd1$水域及水利设施/sd2[5],
           lq6 = sd1$旱地/sd2[6],
           lq7 = sd1$草地/sd2[7],
           lq8 = sd1$水浇地/sd2[8],
           lq9 = sd1$设施农用地/sd2[9],
           lq10 = sd1$矿业用地/sd2[10],
           lq11 = sd1$公共服务用地/sd2[11],
           lq12 = sd1$商服用地 /sd2[12],
           lq13 = sd1$工业用地/sd2[13],
           lq14 = sd1$物流仓储用地/sd2[14])
  
  # library(writexl)
  # write_xlsx(sd_dataset,"sd_dataset.xlsx")

```

```{r}
  library(readxl)
  library(readxl)
  library(tidyverse)
  library(bruceR)
  library(writexl)
  library(ggpubr)
  library(plotly)

  sd_mianji <- sd_dataset[,1:14]
  sd_mianji <- sd_mianji %>% 
    mutate(村庄 = sui_de_initial$QSDWMC )
  sd_mjlong = sd_mianji %>%
    pivot_longer(-村庄, names_to = "地类", values_to = "面积/公亩")
  str(sd_mjlong)
  p1 <- ggboxplot(sd_mjlong, x="地类", y="面积/公亩",fill ="地类",
                  palette = "aaas",#杂志Science的配色
                  sorting = "descending",                   
                  rotate = TRUE,                    
                  ggtheme = theme_bw())+
    theme(legend.position = "none")+
    ylim(0,20001)
  p1
  # ggexport(p1,filename = "pics/14种地类规模.png",
  #          width = 4000,height = 2000,
  #          res = 600)

  
  sd_quweishang <- sd_dataset[,15:28]
  names(sd_quweishang) <- c("科教文卫用地","交通运输用地","林地",
                            "园地","水域及水利设施","旱地","草地",
                            "水浇地","设施农用地","矿业用地",
                            "公共服务用地","商服用地",
                            "工业用地","物流仓储用地")
  sd_quweishang <- sd_quweishang %>% 
    mutate(村庄 = sui_de_initial$QSDWMC )
  sd_longer = sd_quweishang %>%
    pivot_longer(-村庄, names_to = "地类", values_to = "区位商")
  
  p2 <- ggboxplot(sd_longer, x="地类", y="区位商",fill ="地类",
                 palette = "aaas",
                 sorting = "descending",                   
                 rotate = TRUE,                    
                 ggtheme = theme_bw())+
    theme(legend.position = "none")+
    geom_hline(yintercept = 1,linetype = 2,
               color = "red")+
    scale_y_continuous(breaks = 1)+
    ylim(0,10)
  p2
  # ggexport(p,filename = "pics/绥德县14种地类区位商.png",
  #          width = 4000,height = 2000,
  #          res = 600)
```


#  2.层次聚类图美化
```{r}
  library(ggdendro)
  library(ggplot2)
  library(factoextra)
  library(ggpubr)
  library(ggsci)
  library(readxl)
  library(tidyverse)
  #  层次聚类，先生成距离矩阵。
  d1 <- dist(sd_dataset[,15:28],"canberra")
  hc7 <- hclust(d1,"ward.D2")
  tree = as.dendrogram(hc7)
  
  c2 <- cutree(hc7,2)
  table(c2)
  plot(cut(tree, h=25)$upper, horiz=FALSE)
  rect.hclust(hc7,2)
  
  c3 <- cutree(hc7,3)
  table(c3)
  plot(cut(tree, h=25)$upper, horiz=FALSE)
  rect.hclust(hc7,3)
  
  c4 <- cutree(hc7,4)
  table(c4)
  plot(cut(tree, h=25)$upper, horiz=FALSE)
  rect.hclust(hc7,4)
  
  c5 <- cutree(hc7,5)
  table(c5)
  plot(cut(tree, h=25)$upper, horiz=FALSE)
  rect.hclust(hc7,5)
  
  #vignette("ggsci")
  pal_aaas(palette = c("default"), alpha = 1)(5)
  pal_npg(palette = c("nrc"), alpha = 1)(8)

  p52 <- fviz_dend(hc7,k = 2,
                   xlab = "村庄",
                   ylab = "Height",
                   main = "",
                   rect = TRUE,
                   k_colors = c("#3B4992FF","#EE0000FF"),
                   ggtheme = theme_bw())+
    annotate("text", x = 100, y = 32,label = "村庄数:244",colour= "#3B4992FF",size=3)+
    annotate("text", x = 400, y = 48,label = "村庄数:421",colour= "#EE0000FF",size=3) 
  p52
  # ggexport(p52,filename = "pics/聚类谱系图2.png",
  #          width = 3400,height = 3000,
  #          res = 600)
  
  
  p53 <- fviz_dend(hc7,k = 3,
                   xlab = "村庄",
                   ylab = "Height",
                   main = "",
                   rect = TRUE,
                   k_colors = c("#3B4992FF","#EE0000FF","#008B45FF"),
                   ggtheme = theme_bw())+
    annotate("text", x = 110, y = 32,label = "村庄数:244",colour= "#3B4992FF",
             size = 3)+
    annotate("text", x = 300, y = 32,label = "村庄数:149",colour= "#EE0000FF",
             size = 3)+
    annotate("text", x = 500, y = 32,label = "村庄数:272",colour= "#008B45FF",
             size = 3)
  p53
  # ggexport(p53,filename = "pics/聚类谱系图3.png",
  #          width = 3400,height = 3000,
  #          res = 600)
  
  p54 <- fviz_dend(hc7,k = 4,
                   xlab = "村庄",
                   ylab = "Height",
                   main = "",
                   rect = TRUE,
                   k_colors = c("#3B4992FF","#EE0000FF",
                                "#008B45FF","#631879FF"),
                   ggtheme = theme_bw())+
    annotate("text", x = 110, y = 32,label = "村庄数:244",colour= "#3B4992FF",
             size = 3)+
    annotate("text", x = 310, y = 32,label = "村庄数:149",colour= "#EE0000FF",
             size = 3)+
    annotate("text", x = 430, y = 32,label = "村庄数:79",colour= "#008B45FF",
             size = 3)+
    annotate("text", x = 550, y = 28,label = "村庄数:193",colour = "#631879FF",
             size = 3)
  
  
  table(c3)
  table(c5)  
  p54
  # ggexport(p54,filename = "pics/聚类谱系图4.png",
  #          width = 3400,height = 3000,
  #          res = 600)
  
  p55 <- fviz_dend(hc7,k = 5,
                   xlab = "村庄",
                   ylab = "Height",
                   main = "",
                   rect = TRUE,
                   k_colors = c("#3B4992FF","#F39B7FFF",
                                "#EE0000FF",
                                "#008B45FF","#631879FF"),
                   ggtheme = theme_bw())+
    annotate("text", x = 60, y = 32,label = "村庄数:136",colour= "#3B4992FF",
             size = 3)+
    annotate("text", x = 190, y = 28,label = "村庄数:108",colour= "#F39B7FFF",
             size = 3)+
    annotate("text", x = 310, y = 32,label = "村庄数:149",colour= "#EE0000FF",
             size = 3)+
    annotate("text", x = 430, y = 32,label = "村庄数:79",colour= "#008B45FF",
             size = 3)+
    annotate("text", x = 550, y = 28,label = "村庄数:193",colour = "#631879FF",
             size = 3)
  p55
  # ggexport(p55,filename = "pics/聚类谱系图5.png",
  #          width = 3400,height = 3000,
  #          res = 600)
```

#  3.箱线图
```{r}
  library(ggdendro)
  library(ggplot2)
  library(factoextra)
  library(ggpubr)
  library(ggsci)
  library(readxl)
  library(tidyverse)
  sd_dataset_hclust <- read_xlsx("D:/wenyu/Rrojects/sui_de/sui_de_1107/sd_hclust.xlsx")
  table(sd_dataset_hclust$结果_5)
  sdhc1 <-  sd_dataset_hclust %>% 
    filter(结果_5 == 3) 
  sdhc1_mianji <- sdhc1[,c(1:14,35)]
  sdhc1_quweishang <- sdhc1[,c(15:28,35)]
  str(sdhc1_quweishang)
  names(sdhc1_quweishang) <- c("科教文卫用地","交通运输用地","林地",
                               "园地","水域及水利设施","旱地","草地",
                               "水浇地","设施农用地","矿业用地",
                               "公共服务用地","商服用地",
                               "工业用地","物流仓储用地","村庄")
  str(sdhc1_quweishang)
  str(sdhc1_mianji)
  
  ## 先把各地类面积的宽表转成长表
  sdhc1_mjlong = sdhc1_mianji %>%
    pivot_longer(-村庄, names_to = "地类", values_to = "面积/公亩")
  str(sdhc1_mjlong)
  
  ## 基于各地类面积长表，绘制箱线图
  p1 <- ggboxplot(sdhc1_mjlong, x="地类", y="面积/公亩",fill ="地类",
                  palette = "aaas",#杂志Science的配色
                  sorting = "descending",                   
                  rotate = TRUE,                    
                  ggtheme = theme_bw())+
    theme(legend.position = "none")+
    ylim(0,20001)
  p1
  # ggexport(p1,filename = "pics/聚类5对应的136个村庄地类面积.png",
  #          width = 4000,height = 2000,
  #          res = 600)
  
  
  ## 先把各地类区位商的宽表转成长表
  sdhc1_qwsl= sdhc1_quweishang %>%
    pivot_longer(-村庄, names_to = "地类", values_to = "区位商")
  str(sdhc1_qwsl)
  
  ## 基于各地类面积长表，绘制箱线图
  p1 <- ggboxplot(sdhc1_qwsl, x="地类", y="区位商",fill ="地类",
                  palette = "aaas",
                  sorting = "descending",                   
                  rotate = TRUE,                    
                  ggtheme = theme_bw())+
    theme(legend.position = "none")+
    geom_hline(yintercept = 1,linetype = 2,
               color = "red")+
    scale_y_continuous(breaks = 1)+
    ylim(0,5)
  p1
  # ggexport(p1,filename = "pics/聚类5对应的136个村庄地类区位商.png",
  #          width = 4000,height = 2000,
  #          res = 600)
```


